include:
  - compose.yml

services:
  # 👇 Takes up to 1 minute to start!
  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    ports:
      - 8090:8080
    depends_on:
      ollama:
        condition: service_healthy
    environment:
      - OLLAMA_BASE_URL=$OLLAMA_BASE_URL
      - WEBUI_AUTH=False
    restart: on-failure
    healthcheck:
      test: ["CMD", "curl", "-sf", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  redis-insight:
    image: redis/redisinsight:latest
    restart: always
    ports:
      - "5540:5540"
    depends_on:
      redis:
        condition: service_healthy
    environment:
      RI_APP_PORT: 5540
      RI_LOG_LEVEL: debug
      RI_ACCEPT_TERMS_AND_CONDITIONS: true
      # 👇 Does NOT create a DB connection most of the times, create it manually.
      RI_REDIS_HOST: redis
      RI_REDIS_PORT: 6379
      RI_REDIS_ALIAS: "Local Redis (compose)"
      RI_REDIS_USERNAME: default
      RI_REDIS_PASSWORD: "${REDIS_PASSWORD:-}"
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "node",
          "--experimental-default-type=module",
          '-e "console.log((await fetch(''http://localhost:5540/api/health/'')).ok === true && ''healthy'')"',
        ]
      interval: 5s
      timeout: 3s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4:8.4
    restart: always
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - ${PGADMIN_EXPOSED_PORT:-5050}:80
    configs:
      - source: servers.json
        target: /pgadmin4/servers.json
      - source: preferences.json
        target: /pgadmin4/preferences.json

configs:
  preferences.json:
    content: |
      {
        "preferences": {
          "misc:themes:theme": "dark",
          "browser:display:show_system_objects": true,
          "browser:display:confirm_on_refresh_close": false,
          "browser:display:show_user_defined_templates": true
        }
      }
  servers.json:
    content: |
      {
        "Servers": {
          "1": {
            "Group": "Servers",
            "Name": "Smart Novel Database",
            "Host": "postgres",
            "Port": 5432,
            "MaintenanceDB": "${POSTGRES_DB}",
            "Username": "${POSTGRES_USER}",
            "SSLMode": "prefer",
            "BGColor": "#FF4500",
            "FGColor": "#222222",
            "Comment": "This server will connect to the instance we've created in our compose file."
          }
        }
      }
