import { NovelState } from '../enums';

export interface NovelDetails {
  author: string;
  category: string[];
  coverUrl?: string;
  description: string;
  /** @description As of now this is the directory name inside the data folder */
  id: string;
  name: string;
  state: NovelState;
}
export interface INovel {
  id: string;
  name: string;
  author: string;
  category: string[];
  state: NovelState;
  /**
   * @description The ID generated by the Identity Provider
   * @example "230104087265432001"
   */
  ownerId: string;
  coverUrl?: string;
  description: string;
}
